### ISSUE TITLE
Google Team Drive support

### ISSUE THREAD

**Issue by walkonbothsides** [x0b/rcx#115]
#### Pre-Submission checklist

 - [ ] There is no existing issue that already asks for this feature.<br />
       _If no, please add a_ +1, _and maybe a comment if you have more to add._
 - [x] The feature already exists in rclone (on your PC or in Termux)
 - [ ] I am prepared to help make this feature

#### What version of RCX are you using (About -> App version)?

v1.11.4

#### What problem are you trying to solve?

Google Team Drive support

#### What should RCX be able to do differently with help this problem?
import config maybe

**Comment by x0b** [comment]
Thank you for creating an issue. Could you expand or clarify your description? Team drives should work when importing a rclone config file.

**Comment by walkonbothsides** [comment]
As you can see it can't add the Google Team Drive in RCX.I should import a config to make it.
So I hope there will be a direct way to add it without the rclone in terminal.

**Comment by x0b** [comment]
So unfortunately, team drives always require a terminal session. This is because team drives are configured after you login, and there is no interface to programmatically configure the team drives (cf. https://github.com/rclone/rclone/issues/3455).

It is possible to emulate a complete config session - and I did that for the onedrive remote for example - but that mechansim is very maintanance intensive. We already have an issue for your request though: #88.

Until then, you can import a config file where the teamdrive is already configured, e.g. [via Termux](https://github.com/rclone/rclone/wiki/rclone-on-Android-with-Termux).
