### ISSUE TITLE
Exodus is reporting RCX contains 2 trackers (67 tracking Classes)- Microsof Analytics and Microsoft Crashes

### ISSUE THREAD

**Issue by ioogithub** [x0b/rcx#159]
#### Pre-Submission checklist

 - [X] There is no existing issue that already asks for this feature.<br />

#### What version of RCX are you using (About -> App version)?
1.12.1

#### What problem are you trying to solve?
A tracking free rclone experience on the Android platform.

#### What should RCX be able to do differently to help with this problem?
RCX should be free from all user tracking code, telemetry, tracking and recording app usage, calling home activities, sending Microsoft Corp. sensitive data etc.

I can see that Exodus now reports RCX as having 2 trackers:

1. Microsoft Visual Studio App Center Analytics
2. Microsoft Visual Studio App Center Crashes

Exactly what Analytics data is being send to Microsoft? I see there is an opt out for crash reports but how can the user opt out of telemetry tracking data while the app is being used?

While is is good you removed the Google tracking code from the app, didn't you just trade one large data collecting corporation for another one?

How can users of RCX be sure exactly what data is being send to Microsoft? For example, if the user enters sensitive credentials from their rclone.conf how do we know that these details, along with device fingerprinting and all sorts of other privacy violations are not being send to Microsoft? From a user perspective this is a major security concern with an app like RCX.

I would like to use RCX but I can't justify using an app like this that is sending my data to a large 3rd party corporation's servers.

**Comment by x0b** [comment]
This issue has already been addressed in the forum. More details have also always been linked to and available on [x0b.github.io](https://x0b.github.io/). 

While error reports are the basis of maintenance work on RCX, users can of course choose to not contribute. We believe in transparency and do not hide any switches from you or show you any [sad bears](https://old.reddit.com/r/assholedesign/comments/8cfrcm/sad_bear_guilt_trip/) if you say no.

Since we're on the topic of privacy controls: If you have Google Play/GMS installed, Google may be collecting diagnostic data about you. More info in the [Google help](https://support.google.com/accounts/answer/6078260).

Closed as [Won't Fix].
