### ISSUE TITLE
How to build a working APK?

### ISSUE THREAD

**Issue by t0mmar** [x0b/rcx#47]
I'm not sure how to build a working APK, can you provide some instructions how to build from source?  

I can pull the sources down and build an APK, but the resulting app doesn't seem to work.  It stars up, but when I try to add a remote, Dropbox for example, it bails out to the "Remotes" screen (after setting "Remote name" in the first "Dropbox" detail screen after pressing NEXT).

The same flow of adding Dropbox remote works for me with the downloaded release 1.10.1 APK - so the question is, how do I get a working build out of these sources that would allow me to connect to Dropbox, or other remotes?

**Comment by x0b** [comment]
> I can pull the sources down and build an APK, but the resulting app doesn't seem to work.

The app requires a rclone binary compiled for the target device cpu. If you built the one you forked, it should work because it contains the binary in the repo. Mine does not.

> can you provide some instructions how to build from source?

The [Getting Started](https://x0b.github.io/dev/) provides some pointers. Extracting the binaries from the APK should be the fastest method. 

If you need a completely self-built APK I'd use a termux build because it is much easier to set up, which is documented in the [rclone wiki](https://github.com/rclone/rclone/wiki/rclone-on-Android-with-Termux). You must use go1.13+ if you want Android 10 compatibility.

**Comment by t0mmar** [comment]
This is some good info, thanks for sharing! 

From [Getting Started](https://x0b.github.io/dev/):

> There is a plan to automate the source build, since it is required for F-Droid, but there is not much progress yet on that.

^^^ Getting rclone builds integrated with the APK build would be truly great ;)

**Comment by x0b** [comment]
The current version now includes a gradle file for full source builds. I've also updated [the instructions](https://x0b.github.io/dev/).

**Comment by x0b** [comment]
Closing as solved.
