### ISSUE TITLE
Allow MS Office apps to write to documents stored in remotes

### ISSUE THREAD

**Issue by Zvezdin** [x0b/rcx#57]
Currently MS Office documents are opened as read-only. This may be related or directly solved by #8 , but I am unsure.

**Comment by x0b** [comment]
Yes, [#8 will allow this](https://x0b.github.io/docs/#open-a-single-file-intentaction_open_documenthttpsdeveloperandroidcomreferenceandroidcontentintenthtmlaction_open_document), provided that you open the document from within Word or Google Docs - only then will the system grant the required cross-app permissions. 

Releasing that feature has been postponed multiple times now (originally planned for 1.9, now for 1.13/1.14) because it turned out to be very complicated to move this from a cool demo into a usable/reliable feature state.

**Comment by x0b** [comment]
Closing as `v1.12.0` with the first version of this feature has been released.
