### ISSUE TITLE
Unlog

### ISSUE THREAD

**Issue by Xale4n** [x0b/rcx#62]
Hello, i Wonder if it impossible to "unlog" from a remonté and protect or with a password . Because as it IS right now, everyone that has Access to my phone has also Access to my backup files....

Thanks for your help. 

#### Technical Information
<!-- This information helps with finding your problem. However,
rclone: v1.51.0
rcloneExplorer: 1.11.3
android-sdk: 29
android-device: Pixel 3a
android-ndk-abis: arm64-v8a;armeabi-v7a;armeabi
```

**Comment by x0b** [comment]
By creating a remote, you are creating access credentials for that remote. "Unlogging" in that context would mean to delete those credentials, e.g. to delete the remote (which is already possible).

In general, nothing has access to the files on your remotes, **unless you grant something access**:
- If root your phone and allow another app root access, it could access your remotes
- if you give your unlocked phone to someone else you don't trust, that person could access your remotes (you really shouldn't do that) - most phones support multiple user or guest accounts
- if you disable your phone pin/password/lock, everyone can access your remotes (you really shouldn't do that)
- if you serve a remote or folder, other apps can access that remote/folder at the time you are serving it

What I'm saying is that Android will protect your data (including RCX remotes), but only if you let it.

Could you explain your use case with more details? That might help to figure out what kind of protection feature is required here. E.g. what kind of access do you need to prevent? Who or which app should not have access, and under which circumstances?

**Comment by Xale4n** [comment]
Hello,

thank you very much for your answer and your time for such a futile question.

I have cryptomator and when i want to unlock my vault folder, i must enter my passphrase code.

I was just wondering why i don't have to enter my passphrase code or the password of my rclone config  file to unlock my crypted drive.

Would it be possible to not store the rclone config password and that rcx ask me this password anytime i want to access my drive?
Of course rcx could have an option for people that want the password saved on the device.

I think this would be more secure.

Thank you again and sorry if this is not a priority or a feature that can be implemented.

Xalean

**Comment by x0b** [comment]
You question was definitely not futile - I just needed to figure out what you actually needed :)

> Would it be possible to not store the rclone config password and that rcx ask me this password anytime i want to access my drive?

Currently, rclone configurations do not have encryption enabled - [there is issue #12](https://github.com/x0b/rcx/issues/12) for precisely that feature. You can vote on it to move it up the priority queue.

**Comment by Xale4n** [comment]
Thanks for this new answer.

I don't understand. 
First, i must say that i am very new at rclone (It s been 3 days that i am testing rclone).
I don't understand what you are saying because i could set a password for my rclone under my windows computer.

Are you saying that this is not possible under rcx app?

Then could we put a password to this app ? I don't care if the password is on the rclone config or on the app. I only want to put another secure layer on top of the phone pin or identification.

Is this easily possible ?

Thanks.

X.

**Comment by x0b** [comment]
When you set a password with rclone on your computer, rclone **encrypts** its configuration file. When you want to use this encrypted configuration file with rclone, you need to enter your password.

RCX is different. RCX can only use a **unencrypted** configuration file. However, it can _import_ an encrypted configuration file, prompt for the password, immediately decrypt it and then store it **unencrypted**.

The issue I linked, #12, is a plan to remove that difference - if implemented, we would encrypt the configuration files of every RCX user, and optionally allow you to use your own password or pin on top.

Progress has been slow because:
 * rclone does not have a defined interface for configuration encryption
 * cryptography is hard to get right
 * the crypto parameters are only supported on Android Marshmallow (6.0 / API 23), and Lollipop (5.0 / 5.1) has not yet been dropped (but it soon will be, there are < 5 users).
 * and, of course, because RCX is notoriously understaffed - RCX is kept alive by me spending some of my free time on this, not because of an unknown army of volunteers.

**Comment by Xale4n** [comment]
Thank you very much to have taken the time to explain everything to me. :)
You've been very kind.

This is a good software !! I just wondered why this feature wasn't there and now i have my answer !

Keep going on the good work :-)
