### ISSUE TITLE
Crash on RCX startup (unconfirmed)

### ISSUE THREAD

**Issue by gabriellluz** [x0b/rcx#70]
My RCX was working fine. Suddenly when I try to open it again, it just closes like it's crashing or something like that.

Probably, if I clean data and storage, it will work again but how can I provide a log? It might be an important bug.

**Comment by x0b** [comment]
It sounds like there's a crash, though I haven't received a report yet that fits your description. You might be able to enable crash reporting by directly opening the settings menu [as described here](https://x0b.github.io/bug/#the-app-crashes-before-i-can-reach-the-settings).

If you are on a custom ROM without Google Play Services (GMS), you could also [create a bug report](https://developer.android.com/studio/debug/bug-report) by yourself.

**Comment by gabriellluz** [comment]
Done. Enabled. Yes, I'm on a custom ROM using microG. No Google Play Services available to me.

**Comment by x0b** [comment]
Sorry, I must have worded that confusingly. If you don't have Google Play Services, enabling bug reporting will have no effect. 

In that case, you **will have to** manually pull a crash log from your device [as described here](https://developer.android.com/studio/debug/bug-report).

**Comment by gabriellluz** [comment]
Ok. I'll have to postpone this bug. I'll change my ISP at the end of June. I'm trying to access ADB over network, but my modem is locked, my devices can't see each other and also USB not working correctly. Can't detect my phone for some reason. I'll have to wait a little more. I'll close it for now. Same thing happens on my tablet, using Android Nougat, but yes with a custom rom.

**Comment by x0b** [comment]
You don't actually need an ADB connection, just an internet connection to upload your report. 

If you [follow the instructions to create a report on your device](https://developer.android.com/studio/debug/bug-report#bugreportdevice), it will create a bug report by itself. You can then transfer the report via external storage or internet to your computer. 

If you do that, I _highly_ recommend either redacting the report yourself or sending it directly to x0bdev@gmail.com because it is almost guaranteed to contain private data.
