### ISSUE TITLE
Remove Firebase Dependencies

### ISSUE THREAD

**Issue by ioogithub** [x0b/rcx#99]
I just ran Exodus and was very surprised and greatly disappointed to discovered that RCX has a lot of google tracking code integrated in the app!

There is all sorts of google messaging and telemetry database right next to the unprotected rclone.conf file!

My request is that to respect the users privacy and in the spirit of the wonderful rclone project, a clean version of this app be released without the google tracking code frameworks:

Google AdMob
Google Firebase Analytics
Google CrashLytics

I thought I had discovered a solid rclone solution for Android but I had to uninstall the app today.

**Comment by x0b** [comment]
I understand that some users are not comfortable with Crashlytics. Which, among other things, is why [I have created a specific edition of RCX that ships without any telemetry](https://github.com/x0b/rcx/blob/master/app/build.gradle#L49-L53).  I am working with F-Droid towards providing this editon for all users that aren't comfortable with telemetry, especially not Googles'. In fact, running ```gradlew assembleOss``` today will produce a completely new installable APK that is built directly from rclone and RCX sources. 

Just an FYI: Crashlytics works in conjunction with the installed Google Play Services/GMS. Google collects crash data anyway. The frameworks (and the switch in the settings that enables them) only determine if we have whole-process stack traces, which is why I was keeping them around.

That being said, I _also never liked Google tracking_. Which is why the current alpha preview edition of RCX 1.12 does not ship with GMS any more. I am replacing it with a open-source client for Microsoft Appcenter, where we can much better control over what data is collected, and when it is sent.

**Comment by ioogithub** [comment]
Thanks for the detailed and thoughtful answer.

From your Next Version milestone does this mean that the next apk version you release will be free of this Google tracking code? If not how can end users I get a version of RCX apk without the violating code or until the F-Droid version is available?

Do you have a timeline for the next release? With this disheartening discovery as of now I have lost access to my rclone data on Android until you release the next version or until I find another solution.

Also, is the alpha preview only available though joining Google play or other Google groups?

You mentioned you are replacing Firebase with a Microsoft Appcenter analytics. Will this plan apply to the F-Droid version of the app as well? It still seems unnecessary that in order to a user to access their rclone data on Android that a large 3rd party tech giant like Google or Microsoft needs to be involved.

**Comment by x0b** [comment]
> From your Next Version milestone does this mean that the next apk version you release will be free of this Google tracking code?

That ist the plan, yes.

> Do you have a timeline for the next release? 

I've had a major case of feature creep (while also having no time for RCX at all to due to a series of unfortunate events in my personal and professional life), but there will definitely be a new version in November. 

> Also, is the alpha preview only available though joining Google play or other Google groups?

Google Play Alpha receives every new version a few days early for general testing. GitHub only receives full releases and release candidates for major versions. 


> It still seems unnecessary that in order to a user to access their rclone data on Android that a large 3rd party tech giant like Google or Microsoft needs to be involved.

I've evaluated multiple crash logging solutions (ACRA, Countly, Appcenter), and Appcenter is the only one that offers the service at a reasonable price while also having 24/7 operations and security staff. Thats much more than if I would host it myself.

> You mentioned you are replacing Firebase with a Microsoft Appcenter analytics. Will this plan apply to the F-Droid version of the app as well? 

Only if F-Droid allows it. It might actually work without metrics since F-Droid users tend to have deeper technical understanding, but we'll see.

**Comment by x0b** [comment]
Quick update: The old version (v1.11.4) [is now available on F-Droid](https://f-droid.org/en/packages/io.github.x0b.rcx/). Firebase has been removed from the code base and will be replaced in all versions with Microsoft Appcenter in v1.12. 

As per F-Droid rules, F-Droid users will not contribute error reports or anything else. If F-Droid users want to send crash or error logs, they can manually enable that in the settings.

**Comment by x0b** [comment]
Removed in 29b69ef76b065d35653e797fac3c3724651d508c
